# This is a basic workflow to help you get started with Actions

name: Run another repo's script

# Controls when the workflow will run
on:
  push:
    branches: ["main"]
      
jobs:
  script-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout another repository
        uses: actions/checkout@v2
        with:
          repository: LagneshTS/github-training-2
          token: ${{ secrets.GH_PAT }}
          path: other-repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Python script
        run: |
          cd other-repo
          python Script.py

