# This is a basic workflow to help you get started with Actions

name: Comment on Pull Request

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: ["feature-branch"]
      
jobs:
  comment-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Comment on Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"body": "Thank you for your contribution!"}' \
          https://api.github.com/repos/LagneshTS/github-training/issues/$PR_NUMBER/comments

      - name: Make Changes
        run: |
          git config --global user.email "lagneshsekar@gmail.com"
          git config --global user.name "LagneshTS"

          echo "New changes" >> changes.txt
          git add changes.txt
          git commit -m "Add changes"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{secrets.GH_PAT}}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user
          git branch
          git status
          git remote set-url origin https://$GITHUB_TOKEN@github.com/LagneshTS/github-training.git
          git push


